[deps]
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
Gmsh = "705231aa-382f-11e9-3f0c-b7cb4346fdeb"
Gridap = "56d4f2e9-7ea1-5844-9cf6-b9c51ca7ce8e"
GridapGmsh = "3025c34a-b394-11e9-2a55-3fee550c04c8"
GridapSolvers = "6d3209ee-5e3c-4db7-a716-942eb12ed534"
HyperFEM = "ddbf423a-3df4-409e-9685-3dc416cae46c"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[sources]
HyperFEM = {rev = "main", url = "https://github.com/MultiSimOLab/HyperFEM"}
